[v1]
"amp 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["amp"]
"base100 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["base100"]
"basic-http-server 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["basic-http-server"]
"bingrep 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bingrep"]
"cargo-asm 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-asm"]
"cargo-bloat 0.2.0 (git+https://github.com/razrfalcon/cargo-bloat#f38153750a2af383a5b3082a440cef5250f3d7d0)" = ["cargo-bloat"]
"cargo-check 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-check"]
"cargo-edit 0.3.0-beta.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
"cargo-expand 0.3.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-info 0.5.13 (git+https://gitlab.com/imp/cargo-info.git#5384baf2723511f068a002d1b6d0d0ab1121d838)" = ["cargo-info"]
"cargo-modules 0.3.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-modules"]
"cargo-profiler 0.1.5 (git+https://github.com/kernelmachine/cargo-profiler#c665f29aee43328a5a4880e9c3d4da1512125ed5)" = ["cargo-profiler"]
"cargo-readme 2.0.0 (path+file:///home/mxo/Downloads/cache/cargo-readme-2.0.0)" = ["cargo-readme"]
"cargo-show 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-show"]
"cargo-tree 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tree"]
"cargo-update 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"cargo-vendor 0.1.13 (git+https://github.com/alexcrichton/cargo-vendor#f5699e45583673976edbe53072837513aa5eb639)" = ["cargo-vendor"]
"cargo-watch 6.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"cargo-web 0.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-web"]
"changelog-rs 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["changelog-rs"]
"clippy 0.0.187 (git+https://github.com/rust-lang-nursery/rust-clippy#7dbf315cde9993efa1c671011020d0b261bf7fa1)" = ["cargo-clippy", "clippy-driver"]
"cobalt-bin 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cobalt"]
"comrak 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["comrak"]
"csp 0.1.0 (path+file:///home/mxo/Documents/git/github/csp(c%E6%B2%A1%E6%9C%89%E9%80%9A%E8%BF%87%E3%80%82%E3%80%82%EF%BC%89)" = ["csp"]
"exa 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 6.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"fht2p 0.8.1 (git+https://github.com/biluohc/fht2p#72380bef03ccefbb067bcccc919bc73e6e5ef5f4)" = ["fht2p"]
"fselect 0.3.0 (git+https://github.com/jhspetersson/fselect#cf9bf36447d5102e18198aeebe2c3f604bf33451)" = ["fselect"]
"genact 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["genact"]
"hw 0.1.0 (path+file:///home/mxo/Documents/git/github/nsb)" = ["hw"]
"ion-shell 1.0.0-alpha (git+https://github.com/redox-os/ion/#4c2a71fd94f83022e711482eee9c2ee5c1f73506)" = ["ion"]
"loc 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["loc"]
"mdbook 0.0.28 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"mltt 0.1.0 (path+file:///home/mxo/Downloads/cache/mltt)" = ["mltt"]
"neteasy-mv-merge 0.1.0 (path+file:///home/mxo/Downloads/cache/apx)" = ["neteasy-mv-merge"]
"panopticon 0.16.0 (git+https://github.com/das-labor/panopticon.git#43a83efc33b860710ba6b450627d14be5cff04f5)" = ["qtpanopticon"]
"pulldown-cmark 0.1.0 (git+https://github.com/google/pulldown-cmark#8f070be44f97ebc7800f444646e38a62f325d6b3)" = ["pulldown-cmark"]
"racer 2.0.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"ripgrep 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rustsym 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustsym"]
"simple-http-server 0.4.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["simple-http-server"]
"swindon 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["swindon", "swindon-dev"]
"swindon 0.7.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["swindon", "swindon-dev"]
"tealdeer 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 7.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"wasm-gc-cli 0.1.0 (git+https://github.com/alexcrichton/wasm-gc#09fd67afff7080990a2702f5c98eb1aadc600429)" = ["wasm-gc"]
"watchexec 1.8.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["watchexec"]
"wrk 0.1.0 (git+https://github.com/Xudong-Huang/wrk-rs#bf37b00fdcccbc18768a9e42409ee10ed10a76fa)" = ["wrk"]
"xi-core 0.2.0 (path+file:///home/mxo/Downloads/cache/xi-editor/rust)" = ["xi-core"]
"zcs 0.3.6 (git+https://github.com/biluohc/zipcs#c5a4731e59e832e64123b7838829a4a251a294f7)" = ["zcs"]
