[v1]
"base100 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["base100"]
"basic-http-server 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["basic-http-server"]
"bingrep 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bingrep"]
"cargo-asm 0.1.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-asm", "cargo-llvm-ir"]
"cargo-bloat 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-bom 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bom"]
"cargo-bundle 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bundle"]
"cargo-check 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-check"]
"cargo-edit 0.3.0-beta.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
"cargo-expand 0.3.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-info 0.5.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-info"]
"cargo-license 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-license"]
"cargo-modules 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-modules"]
"cargo-readme 2.0.0 (path+file:///home/mxo/Downloads/cache/cargo-readme-2.0.0)" = ["cargo-readme"]
"cargo-show 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-show"]
"cargo-ssearch 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-ssearch"]
"cargo-tree 0.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tree"]
"cargo-update 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"cargo-vendor 0.1.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-vendor"]
"cargo-watch 6.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"cargo-web 0.6.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-web"]
"changelog-rs 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["changelog-rs"]
"clippy 0.0.191 (git+https://github.com/rust-lang-nursery/rust-clippy#976bbe822a8abc438240cbf952550e383cb233ee)" = ["cargo-clippy", "clippy-driver"]
"cobalt-bin 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cobalt"]
"cobalt-bin 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cobalt"]
"comrak 0.2.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["comrak"]
"exa 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 7.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"fht2p 0.8.1 (git+https://github.com/biluohc/fht2p#6fad795e84492a1f1ffa0410c6b150d12ddd1031)" = ["fht2p"]
"fselect 0.3.2 (git+https://github.com/jhspetersson/fselect#d8c6bf8c0fa03fad64f0b91be7778e96a9e6afd8)" = ["fselect"]
"genact 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["genact"]
"gutenberg 0.3.2 (git+https://github.com/Keats/gutenberg#cdaab76e776982b1e50b0491a8ece14531890f8b)" = ["gutenberg"]
"hw 0.1.0 (path+file:///home/mxo/Documents/git/github/nsb)" = ["hw"]
"ion-shell 1.0.0-alpha (git+https://github.com/redox-os/ion/#4c2a71fd94f83022e711482eee9c2ee5c1f73506)" = ["ion"]
"loc 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["loc"]
"mdbook 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"neteasy-mv-merge 0.1.0 (path+file:///home/mxo/Downloads/cache/apx)" = ["neteasy-mv-merge"]
"racer 2.0.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"ripgrep 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rustsym 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustsym"]
"simple-http-server 0.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["simple-http-server"]
"sysinfo-web 0.1.0 (git+https://github.com/onur/sysinfo-web#5a97e9ec88a519c336cb3da6eeaf87d380d58cbf)" = ["sysinfo-web"]
"tealdeer 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 7.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"wasm-bindgen-cli 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-bindgen", "wasm2es6js"]
"wasm-gc 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-gc"]
"watchexec 1.8.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["watchexec"]
"webbench 0.1.0 (git+https://github.com/ksqsf/webbench-rs#3a43dd0d0a267304220fc0d543a33cb8fefdd8ec)" = ["webbench"]
"xi-core 0.2.0 (path+file:///home/mxo/Downloads/cache/xi-editor/rust)" = ["xi-core"]
"zcs 0.3.6 (git+https://github.com/biluohc/zipcs#c5a4731e59e832e64123b7838829a4a251a294f7)" = ["zcs"]
